[build]
  command = "make SITE_SRC_DEST=/opt/site build"
  publish = "opt/site/public"

[context.production.environment]
  HUGO_VERSION = "0.79.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.79.0"
